# TODO: change topicHeader
header = "cocchiagiannuzzi"
data_update = header + "/sensor_data_update"
new_client = header + "/new_client_info"
all_client_get = new_client + "/get"
remove_client = header + "/device_disconnected"
actuator_state_set = header + "/actuator_state/set"
actuator_state = header + "/actuator_state"
influx_db = header + "/master/influx_db"
mysql_db = header + "/master/mysql_db"
